export { VXForm } from "./components/vxform";
export { VXTableFieldConfig, VXFormFieldConfig, VXFormTemplateOptions, VXFormOptions, VXFormInfo, VXTableConfig, VXFormFieldProperty, VXSurveyInfo, VXSurveyPage } from "./components/vxform.field.config";
export { VXFormField } from "./components/vxform.field";
export { VXFormAttributes } from "./components/vxform.attributes";
export { VXFORM_CONFIG, VXFormConfig, ConfigOption, VXFormExtension } from "./services/vxform.config";
export { VXFormBuilder } from "./services/vxform.builder";
export { FieldType, Field } from "./templates/field.type";
export { FieldArrayType } from "./templates/field-array.type";
export { FieldWrapper } from "./templates/field.wrapper";
export { VXFormModule } from "./core.module";
export { defineHiddenProp as ɵdefineHiddenProp } from "./utils";
export { reverseDeepMerge as ɵreverseDeepMerge, clone } from "./utils";
export { isObject } from "./utils";
export { Guid } from "./guid";
export { VXFormCommonService } from "./tools/common";
export { TestBaseUtils } from "./tools/test";
