import { OnInit, EventEmitter, SimpleChanges, ChangeDetectorRef } from "@angular/core";
import { NzTreeComponent } from "ng-zorro-antd/tree";
import { VXFormFieldConfig } from "@vx-form/core";
import { IOrgData, ITreeData, ICheckedTree } from "../../tools/util";
import { DataService } from "../../service/data.service";
export declare class VXFormOrg implements OnInit {
    dataService: DataService;
    private cd;
    fieldConfig: VXFormFieldConfig;
    tag: boolean;
    treeChangeEvent: EventEmitter<any>;
    data: ITreeData[];
    dimension: boolean;
    selectData: ICheckedTree[];
    curOrgId: string;
    readonly selectedNode: ICheckedTree[];
    readonly selectType: string;
    orgData: IOrgData[];
    treeData: ITreeData[];
    controlid: string;
    treeid: string;
    nzTreeComponent: NzTreeComponent | undefined;
    selectedKey: any[];
    skeletonStatus: number;
    constructor(dataService: DataService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    getOrgData(): void;
    getTreeSelectData(): void;
    orgChange(event: any): void;
    treeChange(event: any): void;
    setTreeUnChecked(tree: ITreeData[], key: string): void;
    setTreeChecked(tree: ITreeData[], key: string): void;
}
