import { OnInit, OnChanges, OnDestroy, EventEmitter, SimpleChanges } from "@angular/core";
import { FormGroup } from "@angular/forms";
import { VXFormFieldConfig, VXSurveyInfo, VXFormCommonService } from "@vx-form/core";
import { NzModalService } from "ng-zorro-antd/modal";
import { NzMessageService } from "ng-zorro-antd/message";
import { VXFormAntService } from "../../tools/service";
import { IDesignFormAPI } from "../../tools/util";
import { VXDialogService } from "../../service/dialog.service";
import { DataService } from "../../service/data.service";
import { VXTransferService } from "../../tools/transferService";
export declare class VXSurveyDesignDetail implements OnInit, OnChanges, OnDestroy {
    private message;
    private modalService;
    private vxFormAntService;
    vxDialogService: VXDialogService;
    dataService: DataService;
    vxTransferService: VXTransferService;
    vxFormCommonService: VXFormCommonService;
    formCode: string;
    api: IDesignFormAPI;
    saveEvent: EventEmitter<string>;
    cancelEvent: EventEmitter<string>;
    previewEvent: EventEmitter<string>;
    pageStatus: number;
    form_model: any;
    form_group: FormGroup;
    form_fields: VXFormFieldConfig[];
    vxSurveyInfo: VXSurveyInfo;
    show_setting: boolean;
    questionField: VXFormFieldConfig;
    pageSelectedIndex: number;
    constructor(message: NzMessageService, modalService: NzModalService, vxFormAntService: VXFormAntService, vxDialogService: VXDialogService, dataService: DataService, vxTransferService: VXTransferService, vxFormCommonService: VXFormCommonService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    saveSurvey(): void;
    initFormInfo(): void;
    pageClick(e: number): void;
    addPage(): void;
    deletePage(index: number): void;
    getQuestionListByPageIndex(pageIndex: number): void;
    questionOperational(res: any): void;
    optionOperational(res: any): void;
    addQuestionType(data: any, index?: any): void;
    addQuestionDragDrop(res: any): void;
    readonly formFieldGroup: any[];
}
