import { OnInit, OnChanges, OnDestroy, EventEmitter, SimpleChanges } from "@angular/core";
import { FormGroup } from "@angular/forms";
import { VXFormFieldConfig, VXFormInfo, VXFormCommonService } from "@vx-form/core";
import { NzModalService } from "ng-zorro-antd/modal";
import { NzMessageService } from "ng-zorro-antd/message";
import { VXFormAntService } from "../../tools/service";
import { ICheckedField, IBusinessTable, Itable, IDesignFormAPI } from "../../tools/util";
import { VXDialogService } from "../../service/dialog.service";
import { DataService } from "../../service/data.service";
import { VXAntCommonService } from "../../tools/commonService";
import { VXTransferService } from "../../tools/transferService";
import { VXDesginToFormService } from "../../tools/tableFieldService";
export declare class VXFormDesignDetail implements OnInit, OnChanges, OnDestroy {
    private message;
    private modalService;
    private vxFormAntService;
    vxDialogService: VXDialogService;
    dataService: DataService;
    vxAntCommonService: VXAntCommonService;
    vxTransferService: VXTransferService;
    vxDesginToFormService: VXDesginToFormService;
    vxFormCommonService: VXFormCommonService;
    formCode: string;
    api: IDesignFormAPI;
    saveEvent: EventEmitter<string>;
    cancelEvent: EventEmitter<string>;
    previewEvent: EventEmitter<string>;
    pageStatus: number;
    form_model: any;
    form_group: FormGroup;
    form_fields: VXFormFieldConfig[];
    vxFormInfo: VXFormInfo;
    business_tables: IBusinessTable;
    layout_column: string;
    layout_row: string;
    table_Data: Itable[];
    constructor(message: NzMessageService, modalService: NzModalService, vxFormAntService: VXFormAntService, vxDialogService: VXDialogService, dataService: DataService, vxAntCommonService: VXAntCommonService, vxTransferService: VXTransferService, vxDesginToFormService: VXDesginToFormService, vxFormCommonService: VXFormCommonService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    btnSave(): void;
    btnCancel(): void;
    btnPreview(): void;
    btnDelete(): void;
    btnMoveUp(): void;
    btnMoveDown(): void;
    btnAddFields(): void;
    btnAddRemark(): void;
    btnAddLine(): void;
    btnAddGroup(): void;
    btnColumn(type: number): void;
    btnRow(type: number): void;
    getCheckFields(): ICheckedField[];
    groupBtnMoveUpOrDown(groupField: VXFormFieldConfig, type: string): void;
    groupBtnAddLineRemark(groupField: VXFormFieldConfig, type: string): void;
    groupBtnTableFields(groupField: VXFormFieldConfig): void;
    groupBtnDeleteFields(groupField: VXFormFieldConfig): void;
    initTablesInfo(): void;
    initFormInfo(): void;
    initTableFieldStatus(): void;
    initTablesData(): void;
    selectTableFields(): void;
    getTableMultipleCode(): string;
    editFormFieldConfig(field: VXFormFieldConfig): void;
    deleteFormFieldConfig(field: VXFormFieldConfig): void;
}
