import { EventEmitter, ViewContainerRef, SimpleChanges, ComponentFactoryResolver, OnInit, OnChanges, OnDestroy, DoCheck, AfterContentInit, AfterContentChecked, AfterViewInit, AfterViewChecked, Injector } from "@angular/core";
import { FormGroup } from "@angular/forms";
import { VXFormConfig } from "../services/vxform.config";
import { VXFormFieldConfig, VXFormOptions } from "./vxform.field.config";
export declare class VXFormField implements OnInit, OnChanges, DoCheck, AfterContentInit, AfterContentChecked, AfterViewInit, AfterViewChecked, OnDestroy {
    private vxFormConfig;
    private componentFactoryResolver;
    private injector;
    field: VXFormFieldConfig;
    className: string;
    warnDeprecation: boolean;
    model: any;
    form: FormGroup;
    options: VXFormOptions;
    rownumber: number;
    modelChange: EventEmitter<any>;
    containerRef: ViewContainerRef;
    constructor(vxFormConfig: VXFormConfig, componentFactoryResolver: ComponentFactoryResolver, injector: Injector, hideDeprecation: any);
    ngAfterContentInit(): void;
    ngAfterContentChecked(): void;
    ngAfterViewInit(): void;
    ngAfterViewChecked(): void;
    ngDoCheck(): void;
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    private renderField;
    private triggerHook;
    private attachComponentRef;
}
